pub mod context;

#[derive(Debug, Default)]
pub struct Error {
    message: Option<String>
}

impl Error {
    /// Creates a new `Error` with a message.
    ///
    /// * `message` - The message to display for this error.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: Some(message.into())
        }
    }

    /// Gets the message from an `Error`, or `None` if it doesn't have one.
    pub fn message(&self) -> &Option<String> { 
        &self.message 
    }
}

/// A result type for errors generated by the
/// framework.
pub type Result<T, E = Error> = std::result::Result<T, E>;

pub mod prelude {
    pub use crate::context::{
        Context,
        Plugin,
        Resource,
        CommandResponse,
    };
}
