[workspace]
resolver = "3"
members = [ "crates/tacl", "crates/billing", "crates/documents", "crates/tagui", "crates/training", "crates/tui", "crates/db_commands", "crates/gui", "crates/tacl-new", "crates/core-new"]

[profile.dist]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
strip = true

[workspace.dependencies]
reliquary = {  git = "https://github.com/eupraxia05/reliquary.git", rev = "v0.0.2", features = ["dolmen"] }
dolmen = {  git = "https://github.com/eupraxia05/dolmen.git", rev = "v0.0.1" }

[patch.crates-io]
dolmen = {git = "https://github.com/eupraxia05/dolmen.git", rev = "v0.0.1" }
reliquary = { git = "https://github.com/eupraxia05/reliquary.git", rev = "v0.0.2" }

[workspace.lints.rust]
missing_docs = "allow"

[workspace.lints.rustdoc]
missing_crate_level_docs = "allow"
