//! Common functionality used by other Training
//! Assistant systems.
use std::result;

/// API for interacting with the SQL database.
pub mod db;

/// API for the plugin system.
pub mod context;

/// Various types of errors that can be generated by a `Context`.
#[derive(Debug)]
pub enum Error {
    /// A file did not exist or did not have
    /// sufficient permissions.
    FileError(String),

    /// The SQLite database generated an error.
    DatabaseError(String),

    /// A `Context` was used without being open.
    NoConnectionError,

    /// Another unspecified error.
    UnknownError,
}

/// A result type for errors generated by the
/// framework.
pub type Result<T, E = Error> = result::Result<T, E>;

impl From<rusqlite::Error> for Error {
    fn from(e: rusqlite::Error) -> Self {
        Error::DatabaseError(e.to_string())
    }
}

impl From<std::io::Error> for Error {
    fn from(e: std::io::Error) -> Self {
        Error::FileError(e.to_string())
    }
}

/// Common imports for working with the `framework`
/// crate.
pub mod prelude {
    pub use crate::{
        Error, Result,
        context::{CommandResponse, Context, Plugin, TuiRenderFn},
        db::{
            Client, DbConnection, DbPlugin,
            TableField, RowId, TableConfig, TableRow,
            Trainer,
        },
    };
}
