//! Common functionality used by other Training
//! Assistant systems.
use std::result;

/// API for interacting with the SQL database.
pub mod db;

/// Various types of errors that can be generated by a `Context`.
#[derive(Debug, Default)]
pub struct Error {
    message: Option<String>
}

impl Error {
    /// Creates a new `Error` with a message.
    ///
    /// * `message` - The message to display for this error.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: Some(message.into())
        }
    }

    /// Gets the message from an `Error`, or `None` if it doesn't have one.
    pub fn message(&self) -> &Option<String> { 
        &self.message 
    }
}

impl From<dolmen::Error> for Error {
    fn from(e: dolmen::Error) -> Self {
        Self::new(e.message().clone().unwrap_or_default())
    }
}

impl From<Error> for dolmen::Error {
    fn from(e: Error) -> dolmen::Error {
        dolmen::Error::new(e.message().clone().unwrap_or_default())
    }
}

/// A result type for errors generated by the
/// framework.
pub type Result<T, E = Error> = result::Result<T, E>;

impl From<rusqlite::Error> for Error {
    fn from(e: rusqlite::Error) -> Self {
        Error::new(format!("database error: {}", e.to_string()))
    }
}

impl From<std::io::Error> for Error {
    fn from(e: std::io::Error) -> Self {
        Error::new(format!("file error: {}", e.to_string()))
    }
}

/// Common imports for working with the `framework`
/// crate.
pub mod prelude {
    pub use crate::{
        db::{
            DbConnection, DbPlugin,
            TableField, RowId, TableConfig, TableRow, DbContextExt,
            FieldTypeInfo, DbConfig
        },
    };
}
