[package]
name = "billing"
version = "0.1.0"
edition = "2024"

[dependencies]
latex = "0.3.1"
documents = { path = "../documents" }
db = { version = "0.0.0", path = "../db" }
framework = { version = "0.1.0", path = "../framework" }
clap = "4.5.50"
