[package]
name = "handoutgen"
version = "0.1.0"
edition = "2024"

[dependencies]
latex = {git = "https://github.com/eupraxia05/latex-rs.git"}
directories = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"